package model;
// Generated 14/07/2018 10:59:12 PM by Hibernate Tools 4.3.1



/**
 * DatosUsuario generated by hbm2java
 */
public class DatosUsuario  implements java.io.Serializable {


     private int idDatosUsuario;
     private Usuarios usuarios;
     private String matricula;
     private String nombre;
     private String apellidoPaterno;
     private String apellidoMaterno;
     private Integer telefono;
     private String correo;
     private String numeroSeguro;

    public DatosUsuario() {
    }

	
    public DatosUsuario(int idDatosUsuario, Usuarios usuarios) {
        this.idDatosUsuario = idDatosUsuario;
        this.usuarios = usuarios;
    }
    public DatosUsuario(int idDatosUsuario, Usuarios usuarios, String matricula, String nombre, String apellidoPaterno, String apellidoMaterno, Integer telefono, String correo, String numeroSeguro) {
       this.idDatosUsuario = idDatosUsuario;
       this.usuarios = usuarios;
       this.matricula = matricula;
       this.nombre = nombre;
       this.apellidoPaterno = apellidoPaterno;
       this.apellidoMaterno = apellidoMaterno;
       this.telefono = telefono;
       this.correo = correo;
       this.numeroSeguro = numeroSeguro;
    }
   
    public int getIdDatosUsuario() {
        return this.idDatosUsuario;
    }
    
    public void setIdDatosUsuario(int idDatosUsuario) {
        this.idDatosUsuario = idDatosUsuario;
    }
    public Usuarios getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Usuarios usuarios) {
        this.usuarios = usuarios;
    }
    public String getMatricula() {
        return this.matricula;
    }
    
    public void setMatricula(String matricula) {
        this.matricula = matricula;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellidoPaterno() {
        return this.apellidoPaterno;
    }
    
    public void setApellidoPaterno(String apellidoPaterno) {
        this.apellidoPaterno = apellidoPaterno;
    }
    public String getApellidoMaterno() {
        return this.apellidoMaterno;
    }
    
    public void setApellidoMaterno(String apellidoMaterno) {
        this.apellidoMaterno = apellidoMaterno;
    }
    public Integer getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(Integer telefono) {
        this.telefono = telefono;
    }
    public String getCorreo() {
        return this.correo;
    }
    
    public void setCorreo(String correo) {
        this.correo = correo;
    }
    public String getNumeroSeguro() {
        return this.numeroSeguro;
    }
    
    public void setNumeroSeguro(String numeroSeguro) {
        this.numeroSeguro = numeroSeguro;
    }




}


