package model;
// Generated 14/07/2018 10:59:12 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Grupo generated by hbm2java
 */
public class Grupo  implements java.io.Serializable {


     private String idGrupo;
     private int cupo;
     private Set unidadAprendizajes = new HashSet(0);

    public Grupo() {
    }

	
    public Grupo(String idGrupo, int cupo) {
        this.idGrupo = idGrupo;
        this.cupo = cupo;
    }
    public Grupo(String idGrupo, int cupo, Set unidadAprendizajes) {
       this.idGrupo = idGrupo;
       this.cupo = cupo;
       this.unidadAprendizajes = unidadAprendizajes;
    }
   
    public String getIdGrupo() {
        return this.idGrupo;
    }
    
    public void setIdGrupo(String idGrupo) {
        this.idGrupo = idGrupo;
    }
    public int getCupo() {
        return this.cupo;
    }
    
    public void setCupo(int cupo) {
        this.cupo = cupo;
    }
    public Set getUnidadAprendizajes() {
        return this.unidadAprendizajes;
    }
    
    public void setUnidadAprendizajes(Set unidadAprendizajes) {
        this.unidadAprendizajes = unidadAprendizajes;
    }




}


