package model;
// Generated 14/07/2018 10:59:12 PM by Hibernate Tools 4.3.1



/**
 * HistorialEmergencia generated by hbm2java
 */
public class HistorialEmergencia  implements java.io.Serializable {


     private int idHistorial;
     private Emergencias emergencias;
     private ReporteIncidencia reporteIncidencia;

    public HistorialEmergencia() {
    }

    public HistorialEmergencia(int idHistorial, Emergencias emergencias, ReporteIncidencia reporteIncidencia) {
       this.idHistorial = idHistorial;
       this.emergencias = emergencias;
       this.reporteIncidencia = reporteIncidencia;
    }
   
    public int getIdHistorial() {
        return this.idHistorial;
    }
    
    public void setIdHistorial(int idHistorial) {
        this.idHistorial = idHistorial;
    }
    public Emergencias getEmergencias() {
        return this.emergencias;
    }
    
    public void setEmergencias(Emergencias emergencias) {
        this.emergencias = emergencias;
    }
    public ReporteIncidencia getReporteIncidencia() {
        return this.reporteIncidencia;
    }
    
    public void setReporteIncidencia(ReporteIncidencia reporteIncidencia) {
        this.reporteIncidencia = reporteIncidencia;
    }




}


