package model;
// Generated 14/07/2018 10:59:12 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * HistorialEquipo generated by hbm2java
 */
public class HistorialEquipo  implements java.io.Serializable {


     private int idHistorialEquipo;
     private Date fecha;

    public HistorialEquipo() {
    }

    public HistorialEquipo(int idHistorialEquipo, Date fecha) {
       this.idHistorialEquipo = idHistorialEquipo;
       this.fecha = fecha;
    }
   
    public int getIdHistorialEquipo() {
        return this.idHistorialEquipo;
    }
    
    public void setIdHistorialEquipo(int idHistorialEquipo) {
        this.idHistorialEquipo = idHistorialEquipo;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }




}


