package model;
// Generated 14/07/2018 10:59:12 PM by Hibernate Tools 4.3.1



/**
 * ListaGrupo generated by hbm2java
 */
public class ListaGrupo  implements java.io.Serializable {


     private int idListaGrupo;

    public ListaGrupo() {
    }

    public ListaGrupo(int idListaGrupo) {
       this.idListaGrupo = idListaGrupo;
    }
   
    public int getIdListaGrupo() {
        return this.idListaGrupo;
    }
    
    public void setIdListaGrupo(int idListaGrupo) {
        this.idListaGrupo = idListaGrupo;
    }




}


