package model;
// Generated 14/07/2018 10:59:12 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Material generated by hbm2java
 */
public class Material  implements java.io.Serializable {


     private int idMaterial;
     private String nombre;
     private int cantidad;
     private Set deudas = new HashSet(0);

    public Material() {
    }

	
    public Material(int idMaterial, String nombre, int cantidad) {
        this.idMaterial = idMaterial;
        this.nombre = nombre;
        this.cantidad = cantidad;
    }
    public Material(int idMaterial, String nombre, int cantidad, Set deudas) {
       this.idMaterial = idMaterial;
       this.nombre = nombre;
       this.cantidad = cantidad;
       this.deudas = deudas;
    }
   
    public int getIdMaterial() {
        return this.idMaterial;
    }
    
    public void setIdMaterial(int idMaterial) {
        this.idMaterial = idMaterial;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public int getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(int cantidad) {
        this.cantidad = cantidad;
    }
    public Set getDeudas() {
        return this.deudas;
    }
    
    public void setDeudas(Set deudas) {
        this.deudas = deudas;
    }




}


