package model;
// Generated 14/07/2018 10:59:12 PM by Hibernate Tools 4.3.1



/**
 * ReactivoUtilizado generated by hbm2java
 */
public class ReactivoUtilizado  implements java.io.Serializable {


     private int idReactivoUtilizado;
     private double cantidad;

    public ReactivoUtilizado() {
    }

    public ReactivoUtilizado(int idReactivoUtilizado, double cantidad) {
       this.idReactivoUtilizado = idReactivoUtilizado;
       this.cantidad = cantidad;
    }
   
    public int getIdReactivoUtilizado() {
        return this.idReactivoUtilizado;
    }
    
    public void setIdReactivoUtilizado(int idReactivoUtilizado) {
        this.idReactivoUtilizado = idReactivoUtilizado;
    }
    public double getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(double cantidad) {
        this.cantidad = cantidad;
    }




}


