package model;
// Generated 14/07/2018 10:59:12 PM by Hibernate Tools 4.3.1



/**
 * Reactivos generated by hbm2java
 */
public class Reactivos  implements java.io.Serializable {


     private int idReactivo;
     private String nombre;
     private String tipo;
     private double cantidad;
     private String riesgo;

    public Reactivos() {
    }

    public Reactivos(int idReactivo, String nombre, String tipo, double cantidad, String riesgo) {
       this.idReactivo = idReactivo;
       this.nombre = nombre;
       this.tipo = tipo;
       this.cantidad = cantidad;
       this.riesgo = riesgo;
    }
   
    public int getIdReactivo() {
        return this.idReactivo;
    }
    
    public void setIdReactivo(int idReactivo) {
        this.idReactivo = idReactivo;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }
    public double getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(double cantidad) {
        this.cantidad = cantidad;
    }
    public String getRiesgo() {
        return this.riesgo;
    }
    
    public void setRiesgo(String riesgo) {
        this.riesgo = riesgo;
    }




}


