package model;
// Generated 14/07/2018 10:59:12 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * SesionDeLaboratorio generated by hbm2java
 */
public class SesionDeLaboratorio  implements java.io.Serializable {


     private int idSesion;
     private UnidadAprendizaje unidadAprendizaje;
     private Usuarios usuarios;
     private Date fecha;
     private Set residuoses = new HashSet(0);

    public SesionDeLaboratorio() {
    }

	
    public SesionDeLaboratorio(int idSesion, UnidadAprendizaje unidadAprendizaje, Usuarios usuarios, Date fecha) {
        this.idSesion = idSesion;
        this.unidadAprendizaje = unidadAprendizaje;
        this.usuarios = usuarios;
        this.fecha = fecha;
    }
    public SesionDeLaboratorio(int idSesion, UnidadAprendizaje unidadAprendizaje, Usuarios usuarios, Date fecha, Set residuoses) {
       this.idSesion = idSesion;
       this.unidadAprendizaje = unidadAprendizaje;
       this.usuarios = usuarios;
       this.fecha = fecha;
       this.residuoses = residuoses;
    }
   
    public int getIdSesion() {
        return this.idSesion;
    }
    
    public void setIdSesion(int idSesion) {
        this.idSesion = idSesion;
    }
    public UnidadAprendizaje getUnidadAprendizaje() {
        return this.unidadAprendizaje;
    }
    
    public void setUnidadAprendizaje(UnidadAprendizaje unidadAprendizaje) {
        this.unidadAprendizaje = unidadAprendizaje;
    }
    public Usuarios getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Usuarios usuarios) {
        this.usuarios = usuarios;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public Set getResiduoses() {
        return this.residuoses;
    }
    
    public void setResiduoses(Set residuoses) {
        this.residuoses = residuoses;
    }




}


