package model;
// Generated 14/07/2018 10:59:12 PM by Hibernate Tools 4.3.1



/**
 * Vale generated by hbm2java
 */
public class Vale  implements java.io.Serializable {


     private int idVale;
     private byte[] vale;
     private String status;

    public Vale() {
    }

    public Vale(int idVale, byte[] vale, String status) {
       this.idVale = idVale;
       this.vale = vale;
       this.status = status;
    }
   
    public int getIdVale() {
        return this.idVale;
    }
    
    public void setIdVale(int idVale) {
        this.idVale = idVale;
    }
    public byte[] getVale() {
        return this.vale;
    }
    
    public void setVale(byte[] vale) {
        this.vale = vale;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }




}


