package paquete.sgr.entity.pojos;
// Generated 7/12/2018 03:49:07 PM by Hibernate Tools 4.3.1



/**
 * DatosVale generated by hbm2java
 */
public class DatosVale  implements java.io.Serializable {


     private int idDatosVale;
     private EquipoLaboratorio equipoLaboratorio;
     private Material material;
     private Reactivos reactivos;
     private Vale vale;

    public DatosVale() {
    }

    public DatosVale(int idDatosVale, EquipoLaboratorio equipoLaboratorio, Material material, Reactivos reactivos, Vale vale) {
       this.idDatosVale = idDatosVale;
       this.equipoLaboratorio = equipoLaboratorio;
       this.material = material;
       this.reactivos = reactivos;
       this.vale = vale;
    }
   
    public int getIdDatosVale() {
        return this.idDatosVale;
    }
    
    public void setIdDatosVale(int idDatosVale) {
        this.idDatosVale = idDatosVale;
    }
    public EquipoLaboratorio getEquipoLaboratorio() {
        return this.equipoLaboratorio;
    }
    
    public void setEquipoLaboratorio(EquipoLaboratorio equipoLaboratorio) {
        this.equipoLaboratorio = equipoLaboratorio;
    }
    public Material getMaterial() {
        return this.material;
    }
    
    public void setMaterial(Material material) {
        this.material = material;
    }
    public Reactivos getReactivos() {
        return this.reactivos;
    }
    
    public void setReactivos(Reactivos reactivos) {
        this.reactivos = reactivos;
    }
    public Vale getVale() {
        return this.vale;
    }
    
    public void setVale(Vale vale) {
        this.vale = vale;
    }




}


