package paquete.sgr.entity.pojos;
// Generated 7/12/2018 03:49:07 PM by Hibernate Tools 4.3.1



/**
 * Deuda generated by hbm2java
 */
public class Deuda  implements java.io.Serializable {


     private Integer idDeuda;
     private Equipo equipo;
     private Material material;
     private String observacion;

    public Deuda() {
    }

    public Deuda(Equipo equipo, Material material, String observacion) {
       this.equipo = equipo;
       this.material = material;
       this.observacion = observacion;
    }
   
    public Integer getIdDeuda() {
        return this.idDeuda;
    }
    
    public void setIdDeuda(Integer idDeuda) {
        this.idDeuda = idDeuda;
    }
    public Equipo getEquipo() {
        return this.equipo;
    }
    
    public void setEquipo(Equipo equipo) {
        this.equipo = equipo;
    }
    public Material getMaterial() {
        return this.material;
    }
    
    public void setMaterial(Material material) {
        this.material = material;
    }
    public String getObservacion() {
        return this.observacion;
    }
    
    public void setObservacion(String observacion) {
        this.observacion = observacion;
    }




}


