package paquete.sgr.entity.pojos;
// Generated 24/11/2018 01:04:58 PM by Hibernate Tools 4.3.1



/**
 * EquipoUtilizado generated by hbm2java
 */
public class EquipoUtilizado  implements java.io.Serializable {


     private Integer idEquipoUtilizado;
     private EquipoLaboratorio equipoLaboratorio;
     private Practica practica;

    public EquipoUtilizado() {
    }

    public EquipoUtilizado(EquipoLaboratorio equipoLaboratorio, Practica practica) {
       this.equipoLaboratorio = equipoLaboratorio;
       this.practica = practica;
    }
   
    public Integer getIdEquipoUtilizado() {
        return this.idEquipoUtilizado;
    }
    
    public void setIdEquipoUtilizado(Integer idEquipoUtilizado) {
        this.idEquipoUtilizado = idEquipoUtilizado;
    }
    public EquipoLaboratorio getEquipoLaboratorio() {
        return this.equipoLaboratorio;
    }
    
    public void setEquipoLaboratorio(EquipoLaboratorio equipoLaboratorio) {
        this.equipoLaboratorio = equipoLaboratorio;
    }
    public Practica getPractica() {
        return this.practica;
    }
    
    public void setPractica(Practica practica) {
        this.practica = practica;
    }




}


