package paquete.sgr.entity.pojos;
// Generated 7/12/2018 03:49:07 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Equipo generated by hbm2java
 */
public class Equipo  implements java.io.Serializable {


     private Integer idEquipo;
     private UnidadGrupo unidadGrupo;
     private String nombre;
     private Set deudas = new HashSet(0);
     private Set vales = new HashSet(0);
     private Set listaGrupos = new HashSet(0);

    public Equipo() {
    }

	
    public Equipo(UnidadGrupo unidadGrupo, String nombre) {
        this.unidadGrupo = unidadGrupo;
        this.nombre = nombre;
    }
    public Equipo(UnidadGrupo unidadGrupo, String nombre, Set deudas, Set vales, Set listaGrupos) {
       this.unidadGrupo = unidadGrupo;
       this.nombre = nombre;
       this.deudas = deudas;
       this.vales = vales;
       this.listaGrupos = listaGrupos;
    }
   
    public Integer getIdEquipo() {
        return this.idEquipo;
    }
    
    public void setIdEquipo(Integer idEquipo) {
        this.idEquipo = idEquipo;
    }
    public UnidadGrupo getUnidadGrupo() {
        return this.unidadGrupo;
    }
    
    public void setUnidadGrupo(UnidadGrupo unidadGrupo) {
        this.unidadGrupo = unidadGrupo;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set getDeudas() {
        return this.deudas;
    }
    
    public void setDeudas(Set deudas) {
        this.deudas = deudas;
    }
    public Set getVales() {
        return this.vales;
    }
    
    public void setVales(Set vales) {
        this.vales = vales;
    }
    public Set getListaGrupos() {
        return this.listaGrupos;
    }
    
    public void setListaGrupos(Set listaGrupos) {
        this.listaGrupos = listaGrupos;
    }




}


