package paquete.sgr.entity.pojos;
// Generated 8/11/2018 09:23:46 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Equipo generated by hbm2java
 */
public class Equipo  implements java.io.Serializable {


     private Integer idEquipo;
     private Usuarios usuarios;
     private String nombre;
     private Set deudas = new HashSet(0);
     private Set vales = new HashSet(0);

    public Equipo() {
    }

	
    public Equipo(Usuarios usuarios, String nombre) {
        this.usuarios = usuarios;
        this.nombre = nombre;
    }
    public Equipo(Usuarios usuarios, String nombre, Set deudas, Set vales) {
       this.usuarios = usuarios;
       this.nombre = nombre;
       this.deudas = deudas;
       this.vales = vales;
    }
   
    public Integer getIdEquipo() {
        return this.idEquipo;
    }
    
    public void setIdEquipo(Integer idEquipo) {
        this.idEquipo = idEquipo;
    }
    public Usuarios getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Usuarios usuarios) {
        this.usuarios = usuarios;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set getDeudas() {
        return this.deudas;
    }
    
    public void setDeudas(Set deudas) {
        this.deudas = deudas;
    }
    public Set getVales() {
        return this.vales;
    }
    
    public void setVales(Set vales) {
        this.vales = vales;
    }




}


