package paquete.sgr.entity.pojos;
// Generated 9/11/2018 11:27:59 PM by Hibernate Tools 4.3.1



/**
 * HistorialEmergencia generated by hbm2java
 */
public class HistorialEmergencia  implements java.io.Serializable {


     private Integer idHistorial;
     private Emergencias emergencias;
     private ReporteIncidencia reporteIncidencia;

    public HistorialEmergencia() {
    }

    public HistorialEmergencia(Emergencias emergencias, ReporteIncidencia reporteIncidencia) {
       this.emergencias = emergencias;
       this.reporteIncidencia = reporteIncidencia;
    }
   
    public Integer getIdHistorial() {
        return this.idHistorial;
    }
    
    public void setIdHistorial(Integer idHistorial) {
        this.idHistorial = idHistorial;
    }
    public Emergencias getEmergencias() {
        return this.emergencias;
    }
    
    public void setEmergencias(Emergencias emergencias) {
        this.emergencias = emergencias;
    }
    public ReporteIncidencia getReporteIncidencia() {
        return this.reporteIncidencia;
    }
    
    public void setReporteIncidencia(ReporteIncidencia reporteIncidencia) {
        this.reporteIncidencia = reporteIncidencia;
    }




}


