package paquete.sgr.entity.pojos;
// Generated 8/11/2018 09:23:46 PM by Hibernate Tools 4.3.1



/**
 * ListaGrupo generated by hbm2java
 */
public class ListaGrupo  implements java.io.Serializable {


     private Integer idListaGrupo;
     private UnidadGrupo unidadGrupo;
     private Usuarios usuarios;

    public ListaGrupo() {
    }

    public ListaGrupo(UnidadGrupo unidadGrupo, Usuarios usuarios) {
       this.unidadGrupo = unidadGrupo;
       this.usuarios = usuarios;
    }
   
    public Integer getIdListaGrupo() {
        return this.idListaGrupo;
    }
    
    public void setIdListaGrupo(Integer idListaGrupo) {
        this.idListaGrupo = idListaGrupo;
    }
    public UnidadGrupo getUnidadGrupo() {
        return this.unidadGrupo;
    }
    
    public void setUnidadGrupo(UnidadGrupo unidadGrupo) {
        this.unidadGrupo = unidadGrupo;
    }
    public Usuarios getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Usuarios usuarios) {
        this.usuarios = usuarios;
    }




}


