package paquete.sgr.entity.pojos;
// Generated 16/11/2018 11:10:37 PM by Hibernate Tools 4.3.1



/**
 * ListaGrupo generated by hbm2java
 */
public class ListaGrupo  implements java.io.Serializable {


     private Integer idListaGrupo;
     private String equipo;
     private String unidadGrupo;
     private Usuarios usuarios;

    public ListaGrupo() {
    }

    public ListaGrupo(String equipo, String unidadGrupo, Usuarios usuarios) {
       this.equipo = equipo;
       this.unidadGrupo = unidadGrupo;
       this.usuarios = usuarios;
    }
   
    public Integer getIdListaGrupo() {
        return this.idListaGrupo;
    }
    
    public void setIdListaGrupo(Integer idListaGrupo) {
        this.idListaGrupo = idListaGrupo;
    }
    public String getEquipo() {
        return this.equipo;
    }
    
    public void setEquipo(String equipo) {
        this.equipo = equipo;
    }
    public String getUnidadGrupo() {
        return this.unidadGrupo;
    }
    
    public void setUnidadGrupo(String unidadGrupo) {
        this.unidadGrupo = unidadGrupo;
    }
    public Usuarios getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Usuarios usuarios) {
        this.usuarios = usuarios;
    }




}


