package paquete.sgr.entity.pojos;
// Generated 9/11/2018 11:27:59 PM by Hibernate Tools 4.3.1



/**
 * MaterialUtilizado generated by hbm2java
 */
public class MaterialUtilizado  implements java.io.Serializable {


     private Integer idMaterialUtilizado;
     private Material material;
     private int idDatos;

    public MaterialUtilizado() {
    }

    public MaterialUtilizado(Material material, int idDatos) {
       this.material = material;
       this.idDatos = idDatos;
    }
   
    public Integer getIdMaterialUtilizado() {
        return this.idMaterialUtilizado;
    }
    
    public void setIdMaterialUtilizado(Integer idMaterialUtilizado) {
        this.idMaterialUtilizado = idMaterialUtilizado;
    }
    public Material getMaterial() {
        return this.material;
    }
    
    public void setMaterial(Material material) {
        this.material = material;
    }
    public int getIdDatos() {
        return this.idDatos;
    }
    
    public void setIdDatos(int idDatos) {
        this.idDatos = idDatos;
    }




}


