package paquete.sgr.entity.pojos;
// Generated 16/11/2018 11:10:37 PM by Hibernate Tools 4.3.1



/**
 * ReactivosUtilizadoPractica generated by hbm2java
 */
public class ReactivosUtilizadoPractica  implements java.io.Serializable {


     private Integer idReactivosUtilizado;
     private Practica practica;
     private Reactivos reactivos;
     private int idDatos;

    public ReactivosUtilizadoPractica() {
    }

    public ReactivosUtilizadoPractica(Practica practica, Reactivos reactivos, int idDatos) {
       this.practica = practica;
       this.reactivos = reactivos;
       this.idDatos = idDatos;
    }
   
    public Integer getIdReactivosUtilizado() {
        return this.idReactivosUtilizado;
    }
    
    public void setIdReactivosUtilizado(Integer idReactivosUtilizado) {
        this.idReactivosUtilizado = idReactivosUtilizado;
    }
    public Practica getPractica() {
        return this.practica;
    }
    
    public void setPractica(Practica practica) {
        this.practica = practica;
    }
    public Reactivos getReactivos() {
        return this.reactivos;
    }
    
    public void setReactivos(Reactivos reactivos) {
        this.reactivos = reactivos;
    }
    public int getIdDatos() {
        return this.idDatos;
    }
    
    public void setIdDatos(int idDatos) {
        this.idDatos = idDatos;
    }




}


