package paquete.sgr.entity.pojos;
// Generated 14/11/2018 08:24:45 PM by Hibernate Tools 4.3.1



/**
 * ReactivosUtilizado generated by hbm2java
 */
public class ReactivosUtilizado  implements java.io.Serializable {


     private Integer idReactivosUtilizado;
     private Reactivos reactivos;
     private int idDatos;

    public ReactivosUtilizado() {
    }

    public ReactivosUtilizado(Reactivos reactivos, int idDatos) {
       this.reactivos = reactivos;
       this.idDatos = idDatos;
    }
   
    public Integer getIdReactivosUtilizado() {
        return this.idReactivosUtilizado;
    }
    
    public void setIdReactivosUtilizado(Integer idReactivosUtilizado) {
        this.idReactivosUtilizado = idReactivosUtilizado;
    }
    public Reactivos getReactivos() {
        return this.reactivos;
    }
    
    public void setReactivos(Reactivos reactivos) {
        this.reactivos = reactivos;
    }
    public int getIdDatos() {
        return this.idDatos;
    }
    
    public void setIdDatos(int idDatos) {
        this.idDatos = idDatos;
    }




}


