package paquete.sgr.entity.pojos;
// Generated 8/11/2018 09:23:46 PM by Hibernate Tools 4.3.1



/**
 * ReactivosUtilizado generated by hbm2java
 */
public class ReactivosUtilizado  implements java.io.Serializable {


     private Integer idReactivosUtilizado;
     private DatosPractica datosPractica;
     private Reactivos reactivos;

    public ReactivosUtilizado() {
    }

    public ReactivosUtilizado(DatosPractica datosPractica, Reactivos reactivos) {
       this.datosPractica = datosPractica;
       this.reactivos = reactivos;
    }
   
    public Integer getIdReactivosUtilizado() {
        return this.idReactivosUtilizado;
    }
    
    public void setIdReactivosUtilizado(Integer idReactivosUtilizado) {
        this.idReactivosUtilizado = idReactivosUtilizado;
    }
    public DatosPractica getDatosPractica() {
        return this.datosPractica;
    }
    
    public void setDatosPractica(DatosPractica datosPractica) {
        this.datosPractica = datosPractica;
    }
    public Reactivos getReactivos() {
        return this.reactivos;
    }
    
    public void setReactivos(Reactivos reactivos) {
        this.reactivos = reactivos;
    }




}


