package paquete.sgr.entity.pojos;
// Generated 7/12/2018 03:49:07 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * ReportePractica generated by hbm2java
 */
public class ReportePractica  implements java.io.Serializable {


     private Integer idReportePractica;
     private Usuarios usuarios;
     private byte[] documentoPractica;
     private Date fecha;
     private Double calificacion;
     private String observaciones;
     private String grupo;
     private String practica;

    public ReportePractica() {
    }

	
    public ReportePractica(Usuarios usuarios) {
        this.usuarios = usuarios;
    }
    public ReportePractica(Usuarios usuarios, byte[] documentoPractica, Date fecha, Double calificacion, String observaciones, String grupo, String practica) {
       this.usuarios = usuarios;
       this.documentoPractica = documentoPractica;
       this.fecha = fecha;
       this.calificacion = calificacion;
       this.observaciones = observaciones;
       this.grupo = grupo;
       this.practica = practica;
    }
   
    public Integer getIdReportePractica() {
        return this.idReportePractica;
    }
    
    public void setIdReportePractica(Integer idReportePractica) {
        this.idReportePractica = idReportePractica;
    }
    public Usuarios getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Usuarios usuarios) {
        this.usuarios = usuarios;
    }
    public byte[] getDocumentoPractica() {
        return this.documentoPractica;
    }
    
    public void setDocumentoPractica(byte[] documentoPractica) {
        this.documentoPractica = documentoPractica;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public Double getCalificacion() {
        return this.calificacion;
    }
    
    public void setCalificacion(Double calificacion) {
        this.calificacion = calificacion;
    }
    public String getObservaciones() {
        return this.observaciones;
    }
    
    public void setObservaciones(String observaciones) {
        this.observaciones = observaciones;
    }
    public String getGrupo() {
        return this.grupo;
    }
    
    public void setGrupo(String grupo) {
        this.grupo = grupo;
    }
    public String getPractica() {
        return this.practica;
    }
    
    public void setPractica(String practica) {
        this.practica = practica;
    }




}


