package paquete.sgr.entity.pojos;
// Generated 24/11/2018 01:04:58 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * SesionDeLaboratorio generated by hbm2java
 */
public class SesionDeLaboratorio  implements java.io.Serializable {


     private Integer idSesion;
     private Grupo grupo;
     private UnidadAprendizaje unidadAprendizaje;
     private Date fecha;
     private String docenteAuxiliar;
     private Set residuoses = new HashSet(0);
     private Set reporteIncidencias = new HashSet(0);
     private Set notificacionesSesions = new HashSet(0);
     private Set vales = new HashSet(0);
     private Set historialEquipos = new HashSet(0);
     private Set reactivoUtilizados = new HashSet(0);

    public SesionDeLaboratorio() {
    }

	
    public SesionDeLaboratorio(Grupo grupo, UnidadAprendizaje unidadAprendizaje, Date fecha, String docenteAuxiliar) {
        this.grupo = grupo;
        this.unidadAprendizaje = unidadAprendizaje;
        this.fecha = fecha;
        this.docenteAuxiliar = docenteAuxiliar;
    }
    public SesionDeLaboratorio(Grupo grupo, UnidadAprendizaje unidadAprendizaje, Date fecha, String docenteAuxiliar, Set residuoses, Set reporteIncidencias, Set notificacionesSesions, Set vales, Set historialEquipos, Set reactivoUtilizados) {
       this.grupo = grupo;
       this.unidadAprendizaje = unidadAprendizaje;
       this.fecha = fecha;
       this.docenteAuxiliar = docenteAuxiliar;
       this.residuoses = residuoses;
       this.reporteIncidencias = reporteIncidencias;
       this.notificacionesSesions = notificacionesSesions;
       this.vales = vales;
       this.historialEquipos = historialEquipos;
       this.reactivoUtilizados = reactivoUtilizados;
    }
   
    public Integer getIdSesion() {
        return this.idSesion;
    }
    
    public void setIdSesion(Integer idSesion) {
        this.idSesion = idSesion;
    }
    public Grupo getGrupo() {
        return this.grupo;
    }
    
    public void setGrupo(Grupo grupo) {
        this.grupo = grupo;
    }
    public UnidadAprendizaje getUnidadAprendizaje() {
        return this.unidadAprendizaje;
    }
    
    public void setUnidadAprendizaje(UnidadAprendizaje unidadAprendizaje) {
        this.unidadAprendizaje = unidadAprendizaje;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public String getDocenteAuxiliar() {
        return this.docenteAuxiliar;
    }
    
    public void setDocenteAuxiliar(String docenteAuxiliar) {
        this.docenteAuxiliar = docenteAuxiliar;
    }
    public Set getResiduoses() {
        return this.residuoses;
    }
    
    public void setResiduoses(Set residuoses) {
        this.residuoses = residuoses;
    }
    public Set getReporteIncidencias() {
        return this.reporteIncidencias;
    }
    
    public void setReporteIncidencias(Set reporteIncidencias) {
        this.reporteIncidencias = reporteIncidencias;
    }
    public Set getNotificacionesSesions() {
        return this.notificacionesSesions;
    }
    
    public void setNotificacionesSesions(Set notificacionesSesions) {
        this.notificacionesSesions = notificacionesSesions;
    }
    public Set getVales() {
        return this.vales;
    }
    
    public void setVales(Set vales) {
        this.vales = vales;
    }
    public Set getHistorialEquipos() {
        return this.historialEquipos;
    }
    
    public void setHistorialEquipos(Set historialEquipos) {
        this.historialEquipos = historialEquipos;
    }
    public Set getReactivoUtilizados() {
        return this.reactivoUtilizados;
    }
    
    public void setReactivoUtilizados(Set reactivoUtilizados) {
        this.reactivoUtilizados = reactivoUtilizados;
    }




}


