package paquete.sgr.entity.pojos;
// Generated 20/10/2018 05:28:52 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Usuarios generated by hbm2java
 */
public class Usuarios  implements java.io.Serializable {


     private Integer idUsuarios;
     private Roles roles;
     private String login;
     private String passsword;
     private Set reportePracticas = new HashSet(0);
     private Set practicas = new HashSet(0);
     private Set unidadGrupos = new HashSet(0);
     private Set listaGrupos = new HashSet(0);
     private Set sesionDeLaboratorios = new HashSet(0);
     private Set datosUsuarios = new HashSet(0);

    public Usuarios() {
    }

	
    public Usuarios(Roles roles) {
        this.roles = roles;
    }
    public Usuarios(Roles roles, String login, String passsword, Set reportePracticas, Set practicas, Set unidadGrupos, Set listaGrupos, Set sesionDeLaboratorios, Set datosUsuarios) {
       this.roles = roles;
       this.login = login;
       this.passsword = passsword;
       this.reportePracticas = reportePracticas;
       this.practicas = practicas;
       this.unidadGrupos = unidadGrupos;
       this.listaGrupos = listaGrupos;
       this.sesionDeLaboratorios = sesionDeLaboratorios;
       this.datosUsuarios = datosUsuarios;
    }
   
    public Integer getIdUsuarios() {
        return this.idUsuarios;
    }
    
    public void setIdUsuarios(Integer idUsuarios) {
        this.idUsuarios = idUsuarios;
    }
    public Roles getRoles() {
        return this.roles;
    }
    
    public void setRoles(Roles roles) {
        this.roles = roles;
    }
    public String getLogin() {
        return this.login;
    }
    
    public void setLogin(String login) {
        this.login = login;
    }
    public String getPasssword() {
        return this.passsword;
    }
    
    public void setPasssword(String passsword) {
        this.passsword = passsword;
    }
    public Set getReportePracticas() {
        return this.reportePracticas;
    }
    
    public void setReportePracticas(Set reportePracticas) {
        this.reportePracticas = reportePracticas;
    }
    public Set getPracticas() {
        return this.practicas;
    }
    
    public void setPracticas(Set practicas) {
        this.practicas = practicas;
    }
    public Set getUnidadGrupos() {
        return this.unidadGrupos;
    }
    
    public void setUnidadGrupos(Set unidadGrupos) {
        this.unidadGrupos = unidadGrupos;
    }
    public Set getListaGrupos() {
        return this.listaGrupos;
    }
    
    public void setListaGrupos(Set listaGrupos) {
        this.listaGrupos = listaGrupos;
    }
    public Set getSesionDeLaboratorios() {
        return this.sesionDeLaboratorios;
    }
    
    public void setSesionDeLaboratorios(Set sesionDeLaboratorios) {
        this.sesionDeLaboratorios = sesionDeLaboratorios;
    }
    public Set getDatosUsuarios() {
        return this.datosUsuarios;
    }
    
    public void setDatosUsuarios(Set datosUsuarios) {
        this.datosUsuarios = datosUsuarios;
    }




}


