package modelbase;
// Generated 18/08/2018 08:54:51 PM by Hibernate Tools 4.3.1



/**
 * Deuda generated by hbm2java
 */
public class Deuda  implements java.io.Serializable {


     private int idDeuda;
     private Equipo equipo;
     private Material material;
     private String observacion;

    public Deuda() {
    }

    public Deuda(int idDeuda, Equipo equipo, Material material, String observacion) {
       this.idDeuda = idDeuda;
       this.equipo = equipo;
       this.material = material;
       this.observacion = observacion;
    }
   
    public int getIdDeuda() {
        return this.idDeuda;
    }
    
    public void setIdDeuda(int idDeuda) {
        this.idDeuda = idDeuda;
    }
    public Equipo getEquipo() {
        return this.equipo;
    }
    
    public void setEquipo(Equipo equipo) {
        this.equipo = equipo;
    }
    public Material getMaterial() {
        return this.material;
    }
    
    public void setMaterial(Material material) {
        this.material = material;
    }
    public String getObservacion() {
        return this.observacion;
    }
    
    public void setObservacion(String observacion) {
        this.observacion = observacion;
    }




}


