package modelbase;
// Generated 18/08/2018 08:54:51 PM by Hibernate Tools 4.3.1



/**
 * EquipoUtilizado generated by hbm2java
 */
public class EquipoUtilizado  implements java.io.Serializable {


     private int idEquipoUtilizado;
     private DatosPractica datosPractica;
     private EquipoLaboratorio equipoLaboratorio;

    public EquipoUtilizado() {
    }

    public EquipoUtilizado(int idEquipoUtilizado, DatosPractica datosPractica, EquipoLaboratorio equipoLaboratorio) {
       this.idEquipoUtilizado = idEquipoUtilizado;
       this.datosPractica = datosPractica;
       this.equipoLaboratorio = equipoLaboratorio;
    }
   
    public int getIdEquipoUtilizado() {
        return this.idEquipoUtilizado;
    }
    
    public void setIdEquipoUtilizado(int idEquipoUtilizado) {
        this.idEquipoUtilizado = idEquipoUtilizado;
    }
    public DatosPractica getDatosPractica() {
        return this.datosPractica;
    }
    
    public void setDatosPractica(DatosPractica datosPractica) {
        this.datosPractica = datosPractica;
    }
    public EquipoLaboratorio getEquipoLaboratorio() {
        return this.equipoLaboratorio;
    }
    
    public void setEquipoLaboratorio(EquipoLaboratorio equipoLaboratorio) {
        this.equipoLaboratorio = equipoLaboratorio;
    }




}


