package modelbase;
// Generated 18/08/2018 08:54:51 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Grupo generated by hbm2java
 */
public class Grupo  implements java.io.Serializable {


     private String idGrupo;
     private int cupo;
     private Set eventoses = new HashSet(0);
     private Set listaGrupos = new HashSet(0);
     private Set unidadAprendizajes = new HashSet(0);

    public Grupo() {
    }

	
    public Grupo(String idGrupo, int cupo) {
        this.idGrupo = idGrupo;
        this.cupo = cupo;
    }
    public Grupo(String idGrupo, int cupo, Set eventoses, Set listaGrupos, Set unidadAprendizajes) {
       this.idGrupo = idGrupo;
       this.cupo = cupo;
       this.eventoses = eventoses;
       this.listaGrupos = listaGrupos;
       this.unidadAprendizajes = unidadAprendizajes;
    }
   
    public String getIdGrupo() {
        return this.idGrupo;
    }
    
    public void setIdGrupo(String idGrupo) {
        this.idGrupo = idGrupo;
    }
    public int getCupo() {
        return this.cupo;
    }
    
    public void setCupo(int cupo) {
        this.cupo = cupo;
    }
    public Set getEventoses() {
        return this.eventoses;
    }
    
    public void setEventoses(Set eventoses) {
        this.eventoses = eventoses;
    }
    public Set getListaGrupos() {
        return this.listaGrupos;
    }
    
    public void setListaGrupos(Set listaGrupos) {
        this.listaGrupos = listaGrupos;
    }
    public Set getUnidadAprendizajes() {
        return this.unidadAprendizajes;
    }
    
    public void setUnidadAprendizajes(Set unidadAprendizajes) {
        this.unidadAprendizajes = unidadAprendizajes;
    }




}


