package modelbase;
// Generated 18/08/2018 08:54:51 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Material generated by hbm2java
 */
public class Material  implements java.io.Serializable {


     private int idMaterial;
     private String nombre;
     private int cantidad;
     private byte existenciaInventario;
     private Set materialUtilizados = new HashSet(0);
     private Set deudas = new HashSet(0);

    public Material() {
    }

	
    public Material(int idMaterial, String nombre, int cantidad, byte existenciaInventario) {
        this.idMaterial = idMaterial;
        this.nombre = nombre;
        this.cantidad = cantidad;
        this.existenciaInventario = existenciaInventario;
    }
    public Material(int idMaterial, String nombre, int cantidad, byte existenciaInventario, Set materialUtilizados, Set deudas) {
       this.idMaterial = idMaterial;
       this.nombre = nombre;
       this.cantidad = cantidad;
       this.existenciaInventario = existenciaInventario;
       this.materialUtilizados = materialUtilizados;
       this.deudas = deudas;
    }
   
    public int getIdMaterial() {
        return this.idMaterial;
    }
    
    public void setIdMaterial(int idMaterial) {
        this.idMaterial = idMaterial;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public int getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(int cantidad) {
        this.cantidad = cantidad;
    }
    public byte getExistenciaInventario() {
        return this.existenciaInventario;
    }
    
    public void setExistenciaInventario(byte existenciaInventario) {
        this.existenciaInventario = existenciaInventario;
    }
    public Set getMaterialUtilizados() {
        return this.materialUtilizados;
    }
    
    public void setMaterialUtilizados(Set materialUtilizados) {
        this.materialUtilizados = materialUtilizados;
    }
    public Set getDeudas() {
        return this.deudas;
    }
    
    public void setDeudas(Set deudas) {
        this.deudas = deudas;
    }




}


