package modelbase;
// Generated 18/08/2018 08:54:51 PM by Hibernate Tools 4.3.1



/**
 * MaterialUtilizado generated by hbm2java
 */
public class MaterialUtilizado  implements java.io.Serializable {


     private int idMaterialUtilizado;
     private DatosPractica datosPractica;
     private Material material;

    public MaterialUtilizado() {
    }

    public MaterialUtilizado(int idMaterialUtilizado, DatosPractica datosPractica, Material material) {
       this.idMaterialUtilizado = idMaterialUtilizado;
       this.datosPractica = datosPractica;
       this.material = material;
    }
   
    public int getIdMaterialUtilizado() {
        return this.idMaterialUtilizado;
    }
    
    public void setIdMaterialUtilizado(int idMaterialUtilizado) {
        this.idMaterialUtilizado = idMaterialUtilizado;
    }
    public DatosPractica getDatosPractica() {
        return this.datosPractica;
    }
    
    public void setDatosPractica(DatosPractica datosPractica) {
        this.datosPractica = datosPractica;
    }
    public Material getMaterial() {
        return this.material;
    }
    
    public void setMaterial(Material material) {
        this.material = material;
    }




}


