package modelbase;
// Generated 18/08/2018 08:54:51 PM by Hibernate Tools 4.3.1



/**
 * NotificacionesPractica generated by hbm2java
 */
public class NotificacionesPractica  implements java.io.Serializable {


     private int idNotificacion;
     private Practica practica;
     private String descripcion;
     private byte estado;

    public NotificacionesPractica() {
    }

    public NotificacionesPractica(int idNotificacion, Practica practica, String descripcion, byte estado) {
       this.idNotificacion = idNotificacion;
       this.practica = practica;
       this.descripcion = descripcion;
       this.estado = estado;
    }
   
    public int getIdNotificacion() {
        return this.idNotificacion;
    }
    
    public void setIdNotificacion(int idNotificacion) {
        this.idNotificacion = idNotificacion;
    }
    public Practica getPractica() {
        return this.practica;
    }
    
    public void setPractica(Practica practica) {
        this.practica = practica;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public byte getEstado() {
        return this.estado;
    }
    
    public void setEstado(byte estado) {
        this.estado = estado;
    }




}


