package modelbase;
// Generated 18/08/2018 08:54:51 PM by Hibernate Tools 4.3.1



/**
 * ReactivosUtilizado generated by hbm2java
 */
public class ReactivosUtilizado  implements java.io.Serializable {


     private int idReactivosUtilizado;
     private DatosPractica datosPractica;
     private Reactivos reactivos;

    public ReactivosUtilizado() {
    }

    public ReactivosUtilizado(int idReactivosUtilizado, DatosPractica datosPractica, Reactivos reactivos) {
       this.idReactivosUtilizado = idReactivosUtilizado;
       this.datosPractica = datosPractica;
       this.reactivos = reactivos;
    }
   
    public int getIdReactivosUtilizado() {
        return this.idReactivosUtilizado;
    }
    
    public void setIdReactivosUtilizado(int idReactivosUtilizado) {
        this.idReactivosUtilizado = idReactivosUtilizado;
    }
    public DatosPractica getDatosPractica() {
        return this.datosPractica;
    }
    
    public void setDatosPractica(DatosPractica datosPractica) {
        this.datosPractica = datosPractica;
    }
    public Reactivos getReactivos() {
        return this.reactivos;
    }
    
    public void setReactivos(Reactivos reactivos) {
        this.reactivos = reactivos;
    }




}


