package modelbase;
// Generated 18/08/2018 08:54:51 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Roles generated by hbm2java
 */
public class Roles  implements java.io.Serializable {


     private int idRol;
     private String nombreRol;
     private Set usuarioses = new HashSet(0);

    public Roles() {
    }

	
    public Roles(int idRol) {
        this.idRol = idRol;
    }
    public Roles(int idRol, String nombreRol, Set usuarioses) {
       this.idRol = idRol;
       this.nombreRol = nombreRol;
       this.usuarioses = usuarioses;
    }
   
    public int getIdRol() {
        return this.idRol;
    }
    
    public void setIdRol(int idRol) {
        this.idRol = idRol;
    }
    public String getNombreRol() {
        return this.nombreRol;
    }
    
    public void setNombreRol(String nombreRol) {
        this.nombreRol = nombreRol;
    }
    public Set getUsuarioses() {
        return this.usuarioses;
    }
    
    public void setUsuarioses(Set usuarioses) {
        this.usuarioses = usuarioses;
    }




}


