package modelbase;
// Generated 18/08/2018 08:54:51 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * SesionDeLaboratorio generated by hbm2java
 */
public class SesionDeLaboratorio  implements java.io.Serializable {


     private int idSesion;
     private UnidadAprendizaje unidadAprendizaje;
     private Usuarios usuarios;
     private Date fecha;
     private Set residuoses = new HashSet(0);
     private Set reporteIncidencias = new HashSet(0);
     private Set notificacionesSesions = new HashSet(0);
     private Set vales = new HashSet(0);
     private Set historialEquipos = new HashSet(0);
     private Set reactivoUtilizados = new HashSet(0);

    public SesionDeLaboratorio() {
    }

	
    public SesionDeLaboratorio(int idSesion, UnidadAprendizaje unidadAprendizaje, Usuarios usuarios, Date fecha) {
        this.idSesion = idSesion;
        this.unidadAprendizaje = unidadAprendizaje;
        this.usuarios = usuarios;
        this.fecha = fecha;
    }
    public SesionDeLaboratorio(int idSesion, UnidadAprendizaje unidadAprendizaje, Usuarios usuarios, Date fecha, Set residuoses, Set reporteIncidencias, Set notificacionesSesions, Set vales, Set historialEquipos, Set reactivoUtilizados) {
       this.idSesion = idSesion;
       this.unidadAprendizaje = unidadAprendizaje;
       this.usuarios = usuarios;
       this.fecha = fecha;
       this.residuoses = residuoses;
       this.reporteIncidencias = reporteIncidencias;
       this.notificacionesSesions = notificacionesSesions;
       this.vales = vales;
       this.historialEquipos = historialEquipos;
       this.reactivoUtilizados = reactivoUtilizados;
    }
   
    public int getIdSesion() {
        return this.idSesion;
    }
    
    public void setIdSesion(int idSesion) {
        this.idSesion = idSesion;
    }
    public UnidadAprendizaje getUnidadAprendizaje() {
        return this.unidadAprendizaje;
    }
    
    public void setUnidadAprendizaje(UnidadAprendizaje unidadAprendizaje) {
        this.unidadAprendizaje = unidadAprendizaje;
    }
    public Usuarios getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Usuarios usuarios) {
        this.usuarios = usuarios;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public Set getResiduoses() {
        return this.residuoses;
    }
    
    public void setResiduoses(Set residuoses) {
        this.residuoses = residuoses;
    }
    public Set getReporteIncidencias() {
        return this.reporteIncidencias;
    }
    
    public void setReporteIncidencias(Set reporteIncidencias) {
        this.reporteIncidencias = reporteIncidencias;
    }
    public Set getNotificacionesSesions() {
        return this.notificacionesSesions;
    }
    
    public void setNotificacionesSesions(Set notificacionesSesions) {
        this.notificacionesSesions = notificacionesSesions;
    }
    public Set getVales() {
        return this.vales;
    }
    
    public void setVales(Set vales) {
        this.vales = vales;
    }
    public Set getHistorialEquipos() {
        return this.historialEquipos;
    }
    
    public void setHistorialEquipos(Set historialEquipos) {
        this.historialEquipos = historialEquipos;
    }
    public Set getReactivoUtilizados() {
        return this.reactivoUtilizados;
    }
    
    public void setReactivoUtilizados(Set reactivoUtilizados) {
        this.reactivoUtilizados = reactivoUtilizados;
    }




}


