package modelbase;
// Generated 18/08/2018 08:54:51 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Usuarios generated by hbm2java
 */
public class Usuarios  implements java.io.Serializable {


     private int idUsuarios;
     private Roles roles;
     private String login;
     private String passsword;
     private Set reportePracticas = new HashSet(0);
     private Set practicas = new HashSet(0);
     private Set listaGrupos = new HashSet(0);
     private Set sesionDeLaboratorios = new HashSet(0);
     private Set unidadAprendizajes = new HashSet(0);
     private Set datosUsuarios = new HashSet(0);

    public Usuarios() {
    }

	
    public Usuarios(int idUsuarios, Roles roles) {
        this.idUsuarios = idUsuarios;
        this.roles = roles;
    }
    public Usuarios(int idUsuarios, Roles roles, String login, String passsword, Set reportePracticas, Set practicas, Set listaGrupos, Set sesionDeLaboratorios, Set unidadAprendizajes, Set datosUsuarios) {
       this.idUsuarios = idUsuarios;
       this.roles = roles;
       this.login = login;
       this.passsword = passsword;
       this.reportePracticas = reportePracticas;
       this.practicas = practicas;
       this.listaGrupos = listaGrupos;
       this.sesionDeLaboratorios = sesionDeLaboratorios;
       this.unidadAprendizajes = unidadAprendizajes;
       this.datosUsuarios = datosUsuarios;
    }
   
    public int getIdUsuarios() {
        return this.idUsuarios;
    }
    
    public void setIdUsuarios(int idUsuarios) {
        this.idUsuarios = idUsuarios;
    }
    public Roles getRoles() {
        return this.roles;
    }
    
    public void setRoles(Roles roles) {
        this.roles = roles;
    }
    public String getLogin() {
        return this.login;
    }
    
    public void setLogin(String login) {
        this.login = login;
    }
    public String getPasssword() {
        return this.passsword;
    }
    
    public void setPasssword(String passsword) {
        this.passsword = passsword;
    }
    public Set getReportePracticas() {
        return this.reportePracticas;
    }
    
    public void setReportePracticas(Set reportePracticas) {
        this.reportePracticas = reportePracticas;
    }
    public Set getPracticas() {
        return this.practicas;
    }
    
    public void setPracticas(Set practicas) {
        this.practicas = practicas;
    }
    public Set getListaGrupos() {
        return this.listaGrupos;
    }
    
    public void setListaGrupos(Set listaGrupos) {
        this.listaGrupos = listaGrupos;
    }
    public Set getSesionDeLaboratorios() {
        return this.sesionDeLaboratorios;
    }
    
    public void setSesionDeLaboratorios(Set sesionDeLaboratorios) {
        this.sesionDeLaboratorios = sesionDeLaboratorios;
    }
    public Set getUnidadAprendizajes() {
        return this.unidadAprendizajes;
    }
    
    public void setUnidadAprendizajes(Set unidadAprendizajes) {
        this.unidadAprendizajes = unidadAprendizajes;
    }
    public Set getDatosUsuarios() {
        return this.datosUsuarios;
    }
    
    public void setDatosUsuarios(Set datosUsuarios) {
        this.datosUsuarios = datosUsuarios;
    }




}


