package modelbase;
// Generated 18/08/2018 08:54:51 PM by Hibernate Tools 4.3.1



/**
 * Vale generated by hbm2java
 */
public class Vale  implements java.io.Serializable {


     private int idVale;
     private Equipo equipo;
     private SesionDeLaboratorio sesionDeLaboratorio;
     private byte[] vale;
     private String status;

    public Vale() {
    }

    public Vale(int idVale, Equipo equipo, SesionDeLaboratorio sesionDeLaboratorio, byte[] vale, String status) {
       this.idVale = idVale;
       this.equipo = equipo;
       this.sesionDeLaboratorio = sesionDeLaboratorio;
       this.vale = vale;
       this.status = status;
    }
   
    public int getIdVale() {
        return this.idVale;
    }
    
    public void setIdVale(int idVale) {
        this.idVale = idVale;
    }
    public Equipo getEquipo() {
        return this.equipo;
    }
    
    public void setEquipo(Equipo equipo) {
        this.equipo = equipo;
    }
    public SesionDeLaboratorio getSesionDeLaboratorio() {
        return this.sesionDeLaboratorio;
    }
    
    public void setSesionDeLaboratorio(SesionDeLaboratorio sesionDeLaboratorio) {
        this.sesionDeLaboratorio = sesionDeLaboratorio;
    }
    public byte[] getVale() {
        return this.vale;
    }
    
    public void setVale(byte[] vale) {
        this.vale = vale;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }




}


