package modelobase;
// Generated 5/10/2018 05:18:07 PM by Hibernate Tools 4.3.1



/**
 * DatosUsuario generated by hbm2java
 */
public class DatosUsuario  implements java.io.Serializable {


     private Integer idDatosUsuario;
     private Usuarios usuarios;
     private String identificador;
     private String nombre;
     private String apellidoPaterno;
     private String apellidoMaterno;
     private String telefono;
     private String correo;
     private String numeroSeguro;

    public DatosUsuario() {
    }

	
    public DatosUsuario(Usuarios usuarios) {
        this.usuarios = usuarios;
    }
    public DatosUsuario(Usuarios usuarios, String identificador, String nombre, String apellidoPaterno, String apellidoMaterno, String telefono, String correo, String numeroSeguro) {
       this.usuarios = usuarios;
       this.identificador = identificador;
       this.nombre = nombre;
       this.apellidoPaterno = apellidoPaterno;
       this.apellidoMaterno = apellidoMaterno;
       this.telefono = telefono;
       this.correo = correo;
       this.numeroSeguro = numeroSeguro;
    }
   
    public Integer getIdDatosUsuario() {
        return this.idDatosUsuario;
    }
    
    public void setIdDatosUsuario(Integer idDatosUsuario) {
        this.idDatosUsuario = idDatosUsuario;
    }
    public Usuarios getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Usuarios usuarios) {
        this.usuarios = usuarios;
    }
    public String getIdentificador() {
        return this.identificador;
    }
    
    public void setIdentificador(String identificador) {
        this.identificador = identificador;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellidoPaterno() {
        return this.apellidoPaterno;
    }
    
    public void setApellidoPaterno(String apellidoPaterno) {
        this.apellidoPaterno = apellidoPaterno;
    }
    public String getApellidoMaterno() {
        return this.apellidoMaterno;
    }
    
    public void setApellidoMaterno(String apellidoMaterno) {
        this.apellidoMaterno = apellidoMaterno;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    public String getCorreo() {
        return this.correo;
    }
    
    public void setCorreo(String correo) {
        this.correo = correo;
    }
    public String getNumeroSeguro() {
        return this.numeroSeguro;
    }
    
    public void setNumeroSeguro(String numeroSeguro) {
        this.numeroSeguro = numeroSeguro;
    }




}


