package modelobase;
// Generated 3/10/2018 11:18:56 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * HistorialEquipo generated by hbm2java
 */
public class HistorialEquipo  implements java.io.Serializable {


     private Integer idHistorialEquipo;
     private EquipoLaboratorio equipoLaboratorio;
     private SesionDeLaboratorio sesionDeLaboratorio;
     private Date fecha;

    public HistorialEquipo() {
    }

    public HistorialEquipo(EquipoLaboratorio equipoLaboratorio, SesionDeLaboratorio sesionDeLaboratorio, Date fecha) {
       this.equipoLaboratorio = equipoLaboratorio;
       this.sesionDeLaboratorio = sesionDeLaboratorio;
       this.fecha = fecha;
    }
   
    public Integer getIdHistorialEquipo() {
        return this.idHistorialEquipo;
    }
    
    public void setIdHistorialEquipo(Integer idHistorialEquipo) {
        this.idHistorialEquipo = idHistorialEquipo;
    }
    public EquipoLaboratorio getEquipoLaboratorio() {
        return this.equipoLaboratorio;
    }
    
    public void setEquipoLaboratorio(EquipoLaboratorio equipoLaboratorio) {
        this.equipoLaboratorio = equipoLaboratorio;
    }
    public SesionDeLaboratorio getSesionDeLaboratorio() {
        return this.sesionDeLaboratorio;
    }
    
    public void setSesionDeLaboratorio(SesionDeLaboratorio sesionDeLaboratorio) {
        this.sesionDeLaboratorio = sesionDeLaboratorio;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }




}


