package modelobase;
// Generated 3/10/2018 11:18:56 PM by Hibernate Tools 4.3.1



/**
 * MaterialUtilizado generated by hbm2java
 */
public class MaterialUtilizado  implements java.io.Serializable {


     private Integer idMaterialUtilizado;
     private DatosPractica datosPractica;
     private Material material;

    public MaterialUtilizado() {
    }

    public MaterialUtilizado(DatosPractica datosPractica, Material material) {
       this.datosPractica = datosPractica;
       this.material = material;
    }
   
    public Integer getIdMaterialUtilizado() {
        return this.idMaterialUtilizado;
    }
    
    public void setIdMaterialUtilizado(Integer idMaterialUtilizado) {
        this.idMaterialUtilizado = idMaterialUtilizado;
    }
    public DatosPractica getDatosPractica() {
        return this.datosPractica;
    }
    
    public void setDatosPractica(DatosPractica datosPractica) {
        this.datosPractica = datosPractica;
    }
    public Material getMaterial() {
        return this.material;
    }
    
    public void setMaterial(Material material) {
        this.material = material;
    }




}


