package modelobase;
// Generated 3/10/2018 11:18:56 PM by Hibernate Tools 4.3.1



/**
 * NotificacionesPractica generated by hbm2java
 */
public class NotificacionesPractica  implements java.io.Serializable {


     private Integer idNotificacion;
     private Practica practica;
     private String descripcion;
     private byte estado;

    public NotificacionesPractica() {
    }

    public NotificacionesPractica(Practica practica, String descripcion, byte estado) {
       this.practica = practica;
       this.descripcion = descripcion;
       this.estado = estado;
    }
   
    public Integer getIdNotificacion() {
        return this.idNotificacion;
    }
    
    public void setIdNotificacion(Integer idNotificacion) {
        this.idNotificacion = idNotificacion;
    }
    public Practica getPractica() {
        return this.practica;
    }
    
    public void setPractica(Practica practica) {
        this.practica = practica;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public byte getEstado() {
        return this.estado;
    }
    
    public void setEstado(byte estado) {
        this.estado = estado;
    }




}


