package modelobase;
// Generated 26/08/2018 08:42:52 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Practica generated by hbm2java
 */
public class Practica  implements java.io.Serializable {


     private Integer idPractica;
     private UnidadAprendizaje unidadAprendizaje;
     private Usuarios usuarios;
     private Date creacion;
     private Set notificacionesPracticas = new HashSet(0);
     private Set datosPracticas = new HashSet(0);

    public Practica() {
    }

	
    public Practica(UnidadAprendizaje unidadAprendizaje, Usuarios usuarios, Date creacion) {
        this.unidadAprendizaje = unidadAprendizaje;
        this.usuarios = usuarios;
        this.creacion = creacion;
    }
    public Practica(UnidadAprendizaje unidadAprendizaje, Usuarios usuarios, Date creacion, Set notificacionesPracticas, Set datosPracticas) {
       this.unidadAprendizaje = unidadAprendizaje;
       this.usuarios = usuarios;
       this.creacion = creacion;
       this.notificacionesPracticas = notificacionesPracticas;
       this.datosPracticas = datosPracticas;
    }
   
    public Integer getIdPractica() {
        return this.idPractica;
    }
    
    public void setIdPractica(Integer idPractica) {
        this.idPractica = idPractica;
    }
    public UnidadAprendizaje getUnidadAprendizaje() {
        return this.unidadAprendizaje;
    }
    
    public void setUnidadAprendizaje(UnidadAprendizaje unidadAprendizaje) {
        this.unidadAprendizaje = unidadAprendizaje;
    }
    public Usuarios getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Usuarios usuarios) {
        this.usuarios = usuarios;
    }
    public Date getCreacion() {
        return this.creacion;
    }
    
    public void setCreacion(Date creacion) {
        this.creacion = creacion;
    }
    public Set getNotificacionesPracticas() {
        return this.notificacionesPracticas;
    }
    
    public void setNotificacionesPracticas(Set notificacionesPracticas) {
        this.notificacionesPracticas = notificacionesPracticas;
    }
    public Set getDatosPracticas() {
        return this.datosPracticas;
    }
    
    public void setDatosPracticas(Set datosPracticas) {
        this.datosPracticas = datosPracticas;
    }




}


