package modelobase;
// Generated 3/10/2018 11:18:56 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Reactivos generated by hbm2java
 */
public class Reactivos  implements java.io.Serializable {


     private Integer idReactivo;
     private String nombre;
     private String tipo;
     private double cantidad;
     private byte existenciaInventario;
     private Set reactivosUtilizados = new HashSet(0);
     private Set reactivoUtilizados = new HashSet(0);

    public Reactivos() {
    }

	
    public Reactivos(String nombre, String tipo, double cantidad, byte existenciaInventario) {
        this.nombre = nombre;
        this.tipo = tipo;
        this.cantidad = cantidad;
        this.existenciaInventario = existenciaInventario;
    }
    public Reactivos(String nombre, String tipo, double cantidad, byte existenciaInventario, Set reactivosUtilizados, Set reactivoUtilizados) {
       this.nombre = nombre;
       this.tipo = tipo;
       this.cantidad = cantidad;
       this.existenciaInventario = existenciaInventario;
       this.reactivosUtilizados = reactivosUtilizados;
       this.reactivoUtilizados = reactivoUtilizados;
    }
   
    public Integer getIdReactivo() {
        return this.idReactivo;
    }
    
    public void setIdReactivo(Integer idReactivo) {
        this.idReactivo = idReactivo;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }
    public double getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(double cantidad) {
        this.cantidad = cantidad;
    }
    public byte getExistenciaInventario() {
        return this.existenciaInventario;
    }
    
    public void setExistenciaInventario(byte existenciaInventario) {
        this.existenciaInventario = existenciaInventario;
    }
    public Set getReactivosUtilizados() {
        return this.reactivosUtilizados;
    }
    
    public void setReactivosUtilizados(Set reactivosUtilizados) {
        this.reactivosUtilizados = reactivosUtilizados;
    }
    public Set getReactivoUtilizados() {
        return this.reactivoUtilizados;
    }
    
    public void setReactivoUtilizados(Set reactivoUtilizados) {
        this.reactivoUtilizados = reactivoUtilizados;
    }




}


