package modelobase;
// Generated 30/09/2018 04:25:13 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * UnidadTematica generated by hbm2java
 */
public class UnidadTematica  implements java.io.Serializable {


     private int idUnidadTematica;
     private UnidadAprendizaje unidadAprendizaje;
     private String nombre;
     private Set practicas = new HashSet(0);

    public UnidadTematica() {
    }

	
    public UnidadTematica(int idUnidadTematica, UnidadAprendizaje unidadAprendizaje, String nombre) {
        this.idUnidadTematica = idUnidadTematica;
        this.unidadAprendizaje = unidadAprendizaje;
        this.nombre = nombre;
    }
    public UnidadTematica(int idUnidadTematica, UnidadAprendizaje unidadAprendizaje, String nombre, Set practicas) {
       this.idUnidadTematica = idUnidadTematica;
       this.unidadAprendizaje = unidadAprendizaje;
       this.nombre = nombre;
       this.practicas = practicas;
    }
   
    public int getIdUnidadTematica() {
        return this.idUnidadTematica;
    }
    
    public void setIdUnidadTematica(int idUnidadTematica) {
        this.idUnidadTematica = idUnidadTematica;
    }
    public UnidadAprendizaje getUnidadAprendizaje() {
        return this.unidadAprendizaje;
    }
    
    public void setUnidadAprendizaje(UnidadAprendizaje unidadAprendizaje) {
        this.unidadAprendizaje = unidadAprendizaje;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set getPracticas() {
        return this.practicas;
    }
    
    public void setPracticas(Set practicas) {
        this.practicas = practicas;
    }




}


