package modelobase;
// Generated 3/10/2018 11:18:56 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * UnidadAprendizaje generated by hbm2java
 */
public class UnidadAprendizaje  implements java.io.Serializable {


     private Integer idUnidadAprendizaje;
     private String nombre;
     private Set sesionDeLaboratorios = new HashSet(0);
     private Set unidadTematicas = new HashSet(0);
     private Set unidadGrupos = new HashSet(0);

    public UnidadAprendizaje() {
    }

	
    public UnidadAprendizaje(String nombre) {
        this.nombre = nombre;
    }
    public UnidadAprendizaje(String nombre, Set sesionDeLaboratorios, Set unidadTematicas, Set unidadGrupos) {
       this.nombre = nombre;
       this.sesionDeLaboratorios = sesionDeLaboratorios;
       this.unidadTematicas = unidadTematicas;
       this.unidadGrupos = unidadGrupos;
    }
   
    public Integer getIdUnidadAprendizaje() {
        return this.idUnidadAprendizaje;
    }
    
    public void setIdUnidadAprendizaje(Integer idUnidadAprendizaje) {
        this.idUnidadAprendizaje = idUnidadAprendizaje;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set getSesionDeLaboratorios() {
        return this.sesionDeLaboratorios;
    }
    
    public void setSesionDeLaboratorios(Set sesionDeLaboratorios) {
        this.sesionDeLaboratorios = sesionDeLaboratorios;
    }
    public Set getUnidadTematicas() {
        return this.unidadTematicas;
    }
    
    public void setUnidadTematicas(Set unidadTematicas) {
        this.unidadTematicas = unidadTematicas;
    }
    public Set getUnidadGrupos() {
        return this.unidadGrupos;
    }
    
    public void setUnidadGrupos(Set unidadGrupos) {
        this.unidadGrupos = unidadGrupos;
    }




}


