package modelobase;
// Generated 5/10/2018 05:18:07 PM by Hibernate Tools 4.3.1



/**
 * UnidadGrupo generated by hbm2java
 */
public class UnidadGrupo  implements java.io.Serializable {


     private int idUnidadGrupo;
     private Grupo grupo;
     private UnidadAprendizaje unidadAprendizaje;
     private Usuarios usuarios;

    public UnidadGrupo() {
    }

    public UnidadGrupo(int idUnidadGrupo, Grupo grupo, UnidadAprendizaje unidadAprendizaje, Usuarios usuarios) {
       this.idUnidadGrupo = idUnidadGrupo;
       this.grupo = grupo;
       this.unidadAprendizaje = unidadAprendizaje;
       this.usuarios = usuarios;
    }
   
    public int getIdUnidadGrupo() {
        return this.idUnidadGrupo;
    }
    
    public void setIdUnidadGrupo(int idUnidadGrupo) {
        this.idUnidadGrupo = idUnidadGrupo;
    }
    public Grupo getGrupo() {
        return this.grupo;
    }
    
    public void setGrupo(Grupo grupo) {
        this.grupo = grupo;
    }
    public UnidadAprendizaje getUnidadAprendizaje() {
        return this.unidadAprendizaje;
    }
    
    public void setUnidadAprendizaje(UnidadAprendizaje unidadAprendizaje) {
        this.unidadAprendizaje = unidadAprendizaje;
    }
    public Usuarios getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Usuarios usuarios) {
        this.usuarios = usuarios;
    }




}


